import type { Metadata } from "next";
import { Toaster } from "sonner";
import QueryProvider from "@/components/providers/query-provider";

import "./globals.css";

const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/website-logo.png",
  },
  openGraph: {
    locale: "fa_IR",
    type: "website",
    siteName: "sitename",
    url: baseUrl,
    images: [
      {
        url: `${baseUrl}/logo.png`,
        width: 1200,
        height: 630,
      },
    ],
  },
};

// const iranSans = localFonts({
//   src: [
//     {
//       path: "../../public/font/iranSans-bold.ttf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../../public/font/iranSans-medium.ttf",
//       weight: "400",
//       style: "normal",
//     },
//   ],
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa" suppressHydrationWarning>
      <body
      // className={`${iranSans.className}`}
      >
        <QueryProvider>
          {children}
          <Toaster position="top-center" richColors />
        </QueryProvider>
      </body>
    </html>
  );
}
